"apiVersion: v1\nkind: Service\nmetadata:\n  name: {{ include \"vulken-3d.fullname\"\
  \ . }}\n  labels:\n    {{- include \"vulken-3d.labels\" . | nindent 4 }}\nspec:\n\
  \  type: {{ .Values.service.type }}\n  ports:\n  - port: {{ .Values.service.port\
  \ }}\n    targetPort: http\n    protocol: TCP\n    name: http\n  - port: {{ .Values.service.healthPort\
  \ }}\n    targetPort: health\n    protocol: TCP\n    name: health\n  selector:\n\
  \    {{- include \"vulken-3d.selectorLabels\" . | nindent 4 }}\n"
