#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <cmath>
#include <random>
#include <algorithm>
#include <chrono>

struct VoxelType {
    enum Type { AIR, STONE, GRASS, WATER, TREE };
};

struct Voxel {
    VoxelType::Type type;
    float height;
};

class VoxelWorld {
public:
    int width, height, depth;
    std::vector<std::vector<std::vector<Voxel>>> voxels;

    VoxelWorld(int w, int h, int d) : width(w), height(h), depth(d) {
        voxels.resize(width, std::vector<std::vector<Voxel>>(height, std::vector<Voxel>(depth)));
        generateTerrain();
    }

private:
    float perlinNoise(float x, float z) {
        return (sin(x * 0.1f) + sin(z * 0.1f) + sin((x + z) * 0.05f)) * 0.3f + 0.5f;
    }

    void generateTerrain() {
        std::mt19937 rng(42);
        std::uniform_real_distribution<float> dist(0.0f, 1.0f);

        for (int x = 0; x < width; x++) {
            for (int z = 0; z < depth; z++) {
                float noise = perlinNoise(x, z);
                int surfaceHeight = static_cast<int>(noise * height * 0.6f);

                for (int y = 0; y < height; y++) {
                    if (y < surfaceHeight - 10) {
                        voxels[x][y][z] = {VoxelType::STONE, y / float(height)};
                    } else if (y < surfaceHeight) {
                        voxels[x][y][z] = {VoxelType::GRASS, y / float(height)};
                    } else if (y < height * 0.3f && surfaceHeight < height * 0.35f) {
                        voxels[x][y][z] = {VoxelType::WATER, y / float(height)};
                    } else {
                        voxels[x][y][z] = {VoxelType::AIR, y / float(height)};
                    }
                }

                // Add trees randomly
                if (surfaceHeight > height * 0.2f && dist(rng) < 0.05f) {
                    int treeHeight = std::min(8, height - surfaceHeight - 1);
                    for (int y = surfaceHeight + 1; y <= surfaceHeight + treeHeight; y++) {
                        if (y < height) {
                            voxels[x][y][z] = {VoxelType::TREE, y / float(height)};
                        }
                    }
                }
            }
        }
    }

public:
    void printStats() {
        int airCount = 0, stoneCount = 0, grassCount = 0, waterCount = 0, treeCount = 0;

        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                for (int z = 0; z < depth; z++) {
                    switch (voxels[x][y][z].type) {
                        case VoxelType::AIR: airCount++; break;
                        case VoxelType::STONE: stoneCount++; break;
                        case VoxelType::GRASS: grassCount++; break;
                        case VoxelType::WATER: waterCount++; break;
                        case VoxelType::TREE: treeCount++; break;
                    }
                }
            }
        }

        std::cout << "World Statistics:\n";
        std::cout << "  Air: " << airCount << " voxels\n";
        std::cout << "  Stone: " << stoneCount << " voxels\n";
        std::cout << "  Grass: " << grassCount << " voxels\n";
        std::cout << "  Water: " << waterCount << " voxels\n";
        std::cout << "  Trees: " << treeCount << " voxels\n";
        std::cout << "  Total: " << width * height * depth << " voxels\n";
    }

    void exportToOBJ(const std::string& filename) {
        std::ofstream file(filename);
        if (!file) {
            std::cerr << "Failed to open file: " << filename << std::endl;
            return;
        }

        file << "# Voxel World Export\n";
        file << "# Generated by World Visualizer Demo\n\n";

        int vertexCount = 0;

        // Generate vertices for each voxel
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                for (int z = 0; z < depth; z++) {
                    if (voxels[x][y][z].type != VoxelType::AIR) {
                        // Generate 8 vertices for the cube
                        file << "v " << x << " " << y << " " << z << "\n";
                        file << "v " << (x+1) << " " << y << " " << z << "\n";
                        file << "v " << (x+1) << " " << (y+1) << " " << z << "\n";
                        file << "v " << x << " " << (y+1) << " " << z << "\n";
                        file << "v " << x << " " << y << " " << (z+1) << "\n";
                        file << "v " << (x+1) << " " << y << " " << (z+1) << "\n";
                        file << "v " << (x+1) << " " << (y+1) << " " << (z+1) << "\n";
                        file << "v " << x << " " << (y+1) << " " << (z+1) << "\n";

                        vertexCount += 8;
                    }
                }
            }
        }

        file << "\n# Faces\n";

        // Generate faces (simplified - just basic cubes)
        int currentVertex = 1;
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                for (int z = 0; z < depth; z++) {
                    if (voxels[x][y][z].type != VoxelType::AIR) {
                        // Generate 12 triangular faces for the cube
                        // Bottom face
                        file << "f " << currentVertex << " " << (currentVertex+1) << " " << (currentVertex+2) << "\n";
                        file << "f " << currentVertex << " " << (currentVertex+2) << " " << (currentVertex+3) << "\n";
                        // Top face
                        file << "f " << (currentVertex+4) << " " << (currentVertex+7) << " " << (currentVertex+6) << "\n";
                        file << "f " << (currentVertex+4) << " " << (currentVertex+6) << " " << (currentVertex+5) << "\n";
                        // Front face
                        file << "f " << currentVertex << " " << (currentVertex+4) << " " << (currentVertex+5) << "\n";
                        file << "f " << currentVertex << " " << (currentVertex+5) << " " << (currentVertex+1) << "\n";
                        // Back face
                        file << "f " << (currentVertex+2) << " " << (currentVertex+6) << " " << (currentVertex+7) << "\n";
                        file << "f " << (currentVertex+2) << " " << (currentVertex+7) << " " << (currentVertex+3) << "\n";
                        // Left face
                        file << "f " << currentVertex << " " << (currentVertex+3) << " " << (currentVertex+7) << "\n";
                        file << "f " << currentVertex << " " << (currentVertex+7) << " " << (currentVertex+4) << "\n";
                        // Right face
                        file << "f " << (currentVertex+1) << " " << (currentVertex+5) << " " << (currentVertex+6) << "\n";
                        file << "f " << (currentVertex+1) << " " << (currentVertex+6) << " " << (currentVertex+2) << "\n";

                        currentVertex += 8;
                    }
                }
            }
        }

        std::cout << "World exported to OBJ: " << filename << " (" << vertexCount << " vertices)\n";
    }

    void printHeightmap() {
        std::cout << "\nHeightmap (top view):\n";
        for (int z = 0; z < std::min(depth, 20); z++) {
            for (int x = 0; x < std::min(width, 40); x++) {
                // Find the highest non-air voxel
                int maxHeight = 0;
                for (int y = height - 1; y >= 0; y--) {
                    if (voxels[x][y][z].type != VoxelType::AIR) {
                        maxHeight = y;
                        break;
                    }
                }

                char symbol = '.';
                if (maxHeight > 0) {
                    if (voxels[x][maxHeight][z].type == VoxelType::WATER) symbol = '~';
                    else if (voxels[x][maxHeight][z].type == VoxelType::GRASS) symbol = '#';
                    else if (voxels[x][maxHeight][z].type == VoxelType::STONE) symbol = '*';
                    else if (voxels[x][maxHeight][z].type == VoxelType::TREE) symbol = 'T';
                }
                std::cout << symbol;
            }
            std::cout << "\n";
        }
    }
};

int main(int argc, char* argv[]) {
    std::cout << "Voxel World Visualizer Demo\n";
    std::cout << "==========================\n\n";

    // Parse command line arguments
    int width = 32, height = 32, depth = 32;
    std::string outputFile = "world.obj";
    bool showHeightmap = false;

    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "--help" || arg == "-h") {
            std::cout << "Usage: " << argv[0] << " [options]\n";
            std::cout << "Options:\n";
            std::cout << "  --width W     Set world width (default: 32)\n";
            std::cout << "  --height H    Set world height (default: 32)\n";
            std::cout << "  --depth D     Set world depth (default: 32)\n";
            std::cout << "  --output F    Set output file (default: world.obj)\n";
            std::cout << "  --heightmap   Show heightmap visualization\n";
            std::cout << "  --help, -h    Show this help message\n";
            return 0;
        } else if (arg == "--width" && i + 1 < argc) {
            width = std::stoi(argv[++i]);
        } else if (arg == "--height" && i + 1 < argc) {
            height = std::stoi(argv[++i]);
        } else if (arg == "--depth" && i + 1 < argc) {
            depth = std::stoi(argv[++i]);
        } else if (arg == "--output" && i + 1 < argc) {
            outputFile = argv[++i];
        } else if (arg == "--heightmap") {
            showHeightmap = true;
        }
    }

    std::cout << "Generating world: " << width << "x" << height << "x" << depth << "\n";

    auto start = std::chrono::high_resolution_clock::now();

    VoxelWorld world(width, height, depth);

    auto end = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);

    std::cout << "Generation completed in " << duration.count() << "ms\n\n";

    world.printStats();

    if (showHeightmap) {
        world.printHeightmap();
    }

    world.exportToOBJ(outputFile);

    return 0;
}
